### ISSUE TITLE
FlyTo buttons

### ISSUE THREAD

**Issue by micahnyc** [OpenSpace/OpenSpace-WebGuiFrontend#65]
buttons should be created to use the openspace.pathnavigation.flyTo() command. At least for planets and moons in the solar system.

**Comment by WeirdRubberDuck** [comment]
Related to: https://github.com/OpenSpace/OpenSpace/issues/1854

**Comment by WeirdRubberDuck** [comment]
Closed in 8c3d18a4a2cb1df526e1c3f2ea228013ce89099e
